#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#api_login_check:
  #path: /api/v1/auth

#api_register:
  #path: /api/v1/register
  #controller: App\Controller\ApiController::register
  #Controller: App\Controller\ApiController::auth
#api_register:
#    path: /api/v1/register
app.swagger_ui:
  path: /api/v1/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_refresh_token:
  path: /api/v1/token/refresh